services:
  app1:
    build:
      context: ./src
    image: public.ecr.aws/h5y6i3a7/futbet23:app1
    ports:
      - "3001:3000"
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb+srv://olguitabarriga:olguita@e0.mlkrg.mongodb.net/?retryWrites=true&w=majority&appName=e0

  app2:
    build:
      context: ./src
    image: public.ecr.aws/h5y6i3a7/futbet23:app2
    ports:
      - "3002:3000"
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb+srv://olguitabarriga:olguita@e0.mlkrg.mongodb.net/?retryWrites=true&w=majority&appName=e0

  mqtt-service:
    build:
      context: ./mqtt-service
    image: public.ecr.aws/h5y6i3a7/futbet23:mqtt-service
    depends_on:
      - db
    environment:
      - MQTT_BROKER_URL=mqtt://broker.iic2173.org:9000
      - MQTT_USERNAME=students
      - MQTT_PASSWORD=iic2173-2024-2-students
      - APP_URL=http://app1
    ports:
      - "1884:1884"
    networks:
      - app-network

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  redis-broker:
    image: redis:7
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - app-network

  producer:
    build:
      context: ./workers
    image: public.ecr.aws/h5y6i3a7/futbet23:producer
    command: uvicorn producer:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis-broker:6379/0
      - CELERY_RESULT_BACKEND=redis://redis-broker:6379/0
    depends_on:
      - redis-broker
    networks:
      - app-network

  consumer:
    build:
      context: ./workers
    image: public.ecr.aws/h5y6i3a7/futbet23:consumer
    command: celery -A consumer.celery_app worker --loglevel=INFO --purge --concurrency=1
    environment:
      - CELERY_BROKER_URL=redis://redis-broker:6379/0
      - CELERY_RESULT_BACKEND=redis://redis-broker:6379/0
    depends_on:
      - producer
    networks:
      - app-network

  dashboard:
    build:
      context: ./workers
    image: public.ecr.aws/h5y6i3a7/futbet23:dashboard
    command: bash -c "sleep 10; celery -A consumer.celery_app flower --loglevel=INFO --url_prefix=dashboard;"
    ports:
      - "5555:5555"
    depends_on:
      - consumer
    environment:
      - CELERY_BROKER_URL=redis://redis-broker:6379/0
      - CELERY_RESULT_BACKEND=redis://redis-broker:6379/0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
